name: Notify Teams on PR Events

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Opened Notification to Teams
        if: github.event.action == 'opened'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Pull Request Opened by: '${{ github.event.pull_request.user.login }}'\\nTitle: '${{ github.event.pull_request.title }}'\\nURL: '${{ github.event.pull_request.html_url }}'"}' \
          YOUR_WEBHOOK_URL

      - name: Send PR Closed Notification to Teams
        if: github.event.action == 'closed'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Pull Request Closed by: '${{ github.actor }}'\\nTitle: '${{ github.event.pull_request.title }}'\\nURL: '${{ github.event.pull_request.html_url }}'"}' \
          YOUR_WEBHOOK_URL

      - name: Send PR Reopened Notification to Teams
        if: github.event.action == 'reopened'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Pull Request Reopened by: '${{ github.actor }}'\\nTitle: '${{ github.event.pull_request.title }}'\\nURL: '${{ github.event.pull_request.html_url }}'"}' \
          YOUR_WEBHOOK_URL

      - name: Send PR Updated Notification to Teams
        if: github.event.action == 'synchronize'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Pull Request Updated by: '${{ github.actor }}'\\nTitle: '${{ github.event.pull_request.title }}'\\nURL: '${{ github.event.pull_request.html_url }}'"}' \
          YOUR_WEBHOOK_URL
