name: Notify Teams on PR Events

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: cd Argos && ./gradlew build

      - name: Send PR Failed Notification to Teams
        if: failure()
        run: |
          if [[ ${{ github.event.pull_request.requested_reviewers }} ]]; then
            reviewers="${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}"
          else
            reviewers="No reviewers assigned"
          fi
          
          if [[ ${{ github.event.pull_request.labels }} ]]; then
            labels="${{ join(github.event.pull_request.labels.*.name, ', ') }}"
          else
            labels="No labels assigned"
          fi
          
          curl -X POST -H "Content-type: application/json" \
          --data '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "D50000",
            "summary": "Pull Request Build Failed",
            "sections": [{
                "activityTitle": "Pull Request Build Failed",
                "activitySubtitle": "Failed for: '${{ github.event.pull_request.user.login }}'",
                "facts": [{
                    "name": "Title",
                    "value": "${{ github.event.pull_request.title }}"
                }, {
                    "name": "URL",
                    "value": "${{ github.event.pull_request.html_url }}"
                }, {
                    "name": "Added Lines",
                    "value": "${{ github.event.pull_request.additions }}"
                }, {
                    "name": "Deleted Lines",
                    "value": "${{ github.event.pull_request.deletions }}"
                }, {
                    "name": "Opened by",
                    "value": "${{ github.event.pull_request.user.login }}"
                }, {
                    "name": "Reviewer(s)",
                    "value": "'"${reviewers}"'"
                }, {
                    "name": "Label(s)",
                    "value": "'"${labels}"'"
                }]
            }]
          }' \
          https://prod-03.westus.logic.azure.com:443/workflows/d380d1c496354d14981b088a9586ba59/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Ukdu_OxO-D6FbIu78BTmRRnDLHEFSwgpvbzF2gMu-X4

  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Opened Notification to Teams
        if: github.event.action == 'opened'
        run: |
          if [[ ${{ github.event.pull_request.requested_reviewers }} ]]; then
            reviewers="${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}"
          else
            reviewers="No reviewers assigned"
          fi
          
          if [[ ${{ github.event.pull_request.labels }} ]]; then
            labels="${{ join(github.event.pull_request.labels.*.name, ', ') }}"
          else
            labels="No labels assigned"
          fi

          curl -X POST -H "Content-type: application/json" \
          --data '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0076D7",
            "summary": "Pull Request Opened",
            "sections": [{
                "activityTitle": "Pull Request Opened",
                "activitySubtitle": "Opened by: '${{ github.event.pull_request.user.login }}'",
                "facts": [{
                    "name": "Title",
                    "value": "${{ github.event.pull_request.title }}"
                }, {
                    "name": "URL",
                    "value": "${{ github.event.pull_request.html_url }}"
                }, {
                    "name": "Added Lines",
                    "value": "${{ github.event.pull_request.additions }}"
                }, {
                    "name": "Deleted Lines",
                    "value": "${{ github.event.pull_request.deletions }}"
                }, {
                    "name": "Reviewer(s)",
                    "value": "'"${reviewers}"'"
                }, {
                    "name": "Label(s)",
                    "value": "'"${labels}"'"
                }]
            }]
          }' \
          https://prod-03.westus.logic.azure.com:443/workflows/d380d1c496354d14981b088a9586ba59/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Ukdu_OxO-D6FbIu78BTmRRnDLHEFSwgpvbzF2gMu-X4

      - name: Send PR Merged Notification to Teams
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          if [[ ${{ github.event.pull_request.requested_reviewers }} ]]; then
            reviewers="${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}"
          else
            reviewers="No reviewers assigned"
          fi
          
          if [[ ${{ github.event.pull_request.labels }} ]]; then
            labels="${{ join(github.event.pull_request.labels.*.name, ', ') }}"
          else
            labels="No labels assigned"
          fi

          curl -X POST -H "Content-type: application/json" \
          --data '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "4CAF50",
            "summary": "Pull Request Merged",
            "sections": [{
                "activityTitle": "Pull Request Merged",
                "activitySubtitle": "Merged by: '${{ github.event.pull_request.merged_by.login }}'",
                "facts": [{
                    "name": "Title",
                    "value": "${{ github.event.pull_request.title }}"
                }, {
                    "name": "URL",
                    "value": "${{ github.event.pull_request.html_url }}"
                }, {
                    "name": "Added Lines",
                    "value": "${{ github.event.pull_request.additions }}"
                }, {
                    "name": "Deleted Lines",
                    "value": "${{ github.event.pull_request.deletions }}"
                }, {
                    "name": "Reviewer(s)",
                    "value": "'"${reviewers}"'"
                }, {
                    "name": "Label(s)",
                    "value": "'"${labels}"'"
                }]
            }]
          }' \
          https://prod-03.westus.logic.azure.com:443/workflows/d380d1c496354d14981b088a9586ba59/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Ukdu_OxO-D6FbIu78BTmRRnDLHEFSwgpvbzF2gMu-X4

      - name: Send PR Closed Notification to Teams
        if: github.event.action == 'closed' && github.event.pull_request.merged == false
        run: |
          if [[ ${{ github.event.pull_request.requested_reviewers }} ]]; then
            reviewers="${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}"
          else
            reviewers="No reviewers assigned"
          fi
          
          if [[ ${{ github.event.pull_request.labels }} ]]; then
            labels="${{ join(github.event.pull_request.labels.*.name, ', ') }}"
          else
            labels="No labels assigned"
          fi

          curl -X POST -H "Content-type: application/json" \
          --data '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "FF9800",
            "summary": "Pull Request Closed",
            "sections": [{
                "activityTitle": "Pull Request Closed",
                "activitySubtitle": "Closed by: '${{ github.actor }}'",
                "facts": [{
                    "name": "Title",
                    "value": "${{ github.event.pull_request.title }}"
                }, {
                    "name": "URL",
                    "value": "${{ github.event.pull_request.html_url }}"
                }, {
                    "name": "Reason",
                    "value": "Closed without merging"
                }, {
                    "name": "Added Lines",
                    "value": "${{ github.event.pull_request.additions }}"
                }, {
                    "name": "Deleted Lines",
                    "value": "${{ github.event.pull_request.deletions }}"
                }, {
                    "name": "Opened by",
                    "value": "${{ github.event.pull_request.user.login }}"
                }, {
                    "name": "Reviewer(s)",
                    "value": "'"${reviewers}"'"
                }, {
                    "name": "Label(s)",
                    "value": "'"${labels}"'"
                }]
            }]
          }' \
          https://prod-03.westus.logic.azure.com:443/workflows/d380d1c496354d14981b088a9586ba59/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Ukdu_OxO-D6FbIu78BTmRRnDLHEFSwgpvbzF2gMu-X4
